{{- if and .Values.enabled (not .Values.jetstream.existingSecret) }}
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nats-surveyor
  namespace: {{ .Release.Namespace }}
data:
  rides.json: |-
    {
    "name":       "{{ .Values.jetstream.account }}"
    }
{{- end }}